language: python
dist: bionic
python:
  - "3.5"
  - "3.6"
  - "3.7"
  - "3.8"
  - "3.9-dev"

addons:
  apt:
    packages:
    - debhelper
    - python3-all
    - mypy

install:
  - pip install mypy

script:
  - make test
  - make mypy
  - make GPG=true deb-pkg
