language: python
dist: bionic
python:
  - "3.5"
  - "3.6"
  - "3.7"
  - "3.8"
  - "3.9-dev"

install:
  - pip install mypy
  - apt-get -y install debhelper python3-all mypy

script:
  - make test
  - make mypy
  - make GPG=true deb-pkg
