site_name: typedload
site_dir: html
site_description: typedload documentation — a python module to load untyped data into typed data structures
site_author: Salvo 'LtWorf' Tomaselli <tiposchi@tiscali.it>
copyright: Copyright (C) 2018-2023 Salvo "LtWorf" Tomaselli
theme: readthedocs
use_directory_urls: false
nav:
    - Home: README.md
    #- Origin story: origin_story.md
    - Changelog: CHANGELOG.md
    - Using typedload:
        - Examples: examples.md
        - Supported types: supported_types.md
        - Errors: errors.md
        - Deferred evaluation of types: deferred_evaluation.md
    - Docstrings:
        - typedload: typedload_docgen.md
        - typedload.dataloader: typedload.dataloader_docgen.md
        - typedload.datadumper: typedload.datadumper_docgen.md
        - typedload.typechecks: typedload.typechecks_docgen.md
        - typedload.exceptions: typedload.exceptions_docgen.md
    - Comparisons:
        - Why typedload: comparisons.md
        - Performance: performance.md
    - Contributors:
        - Contributing: CONTRIBUTING.md
        - Code of conduct: CODE_OF_CONDUCT.md
    - Links:
        - Git: https://github.com/ltworf/typedload/
        - Downloads: https://github.com/ltworf/typedload/releases
        - Bug reports: https://github.com/ltworf/typedload/issues
        - Debian package: https://packages.debian.org/search?keywords=python3-typedload
        - Pypi package: https://pypi.org/project/typedload/
        - Pypi stats: https://pypistats.org/packages/typedload
    - Other:
        - Versioning scheme: version_numbers.md
